var data = {
  'MIRAFLORES': [
	  	{
		  name: 'Maido',
		  adress: 'Calle San Martin 399, Miraflores 15074, Peru',
		  openingHours: 'De Lunes a Sabado de 09.00 a 23.00',
		 	typeOfFood: 'internacional',
      averageCost: '$$$$',
      delivery: false,
      image: '../assets/images/maido.jpg',
      rating: 'Espectacular , muy bueno',
		  },
	  	{
      name: 'La lucha sangucheria',
      adress: 'Av. Sta. Cruz 847, Miraflores 15074, Peru',
      openingHours: 'Normalmente de 8.00am a 1.00am',
      typeOfFood: 'peruana',
      averageCost: ' $ - $$',
      delivery: true,
      image: '../assets/images/la-lucha.jpg',
      rating: 'Comida rica y saludable',
    },
    {
      name: 'Taquería No te rajes',
      adress: '18, Av. Alfredo Benavides 1083, Miraflores, Peru',
      openingHours: 'Todos los dias de 12:00 a 24:00',
      typeOfFood: 'internacional',
      averageCost: '$',
      delivery: true,
      image: '../assets/images/no-te-rajes.jpg',
      rating: 'La mejor opción para degustar comida mexicana',
    },
    {
      name: 'La Rosa Náutica',
		  adress: 'Espigón Miraflores, Lima 18, Circuito de Playas, Miraflores, Peru',
      openingHours: 'Todos los dias de 12:00 a 24:00',
      typeOfFood: 'peruana',
      averageCost: '$$$$',
      delivery: false,
      image: '../assets/images/rosa-nautica.jpg',
      rating: 'Excelente atención',
    },
    {
      name: 'Panchita',
      adress: 'Calle 2 de Mayo 298, Miraflores 15074, Peru',
      openingHours: 'Todos los dias de 12:00 a 24:00',
      typeOfFood: 'peruana',
      averageCost: '$$ - $$$',
      delivery: true,
      image: '../assets/images/panchita.jpg',
      rating: 'Inigualable',
    },
  ],
  'SURCO': [
    {
      name: 'El Encanto Amazonico',
      adress: 'Av. Alfredo Benavides 4001, Santiago de Surco 15038, Peru',
      openingHours: 'Todos los dias de 8:00 a 22:00',
      typeOfFood: 'peruana',
      averageCost: '$$ - $$$',
      delivery: true,
      image: '../assets/images/encanto-amazonico.jpg',
      rating: 'Excelente opcion',
    },
    {
      name: 'Gambatte',
      adress: 'Simón Salguero 460, Distrito de Lima 15048, Peru',
      openingHours: 'Martes a Sábado de 12:00 a 15:30 y de 18:30 a 23:00',
      typeOfFood: 'internacional',
      averageCost: '$',
      delivery: true,
      image: '../assets/images/gambatte.jpg',
      rating: 'Muy buena calidad y tamaño',
    },
    {
      name: 'GURU Indian&Pakistani Cuisine',
      adress: 'Av. Alfredo Benavides 4518, Santiago de Surco 15039, Peru',
      openingHours: 'Todos los días de 12:00 a 23:00',
      typeOfFood: 'internacional',
      averageCost: '$$ - $$$',
      delivery: true,
      image: '../assets/images/guru.jpg',
      rating: 'Delicioso! Excelente relación calidad precio',
    },
    {
      name: 'Chifa Choy Tac',
      adress: 'Avenida Alfredo Benavides Diez Canseco 3801, Santiago de Surco 15038, Peru',
      openingHours: 'Todos los días de 12:00 a 16:00 y de 18:30 a 23:30',
      typeOfFood: 'internacional',
      averageCost: '$$ - $$$',
      delivery: true,
      image: '../assets/images/choy-tac.jpeg',
      rating: 'Calidad y calidez',
    },
    {
      name: 'Maretazo',
      adress: 'Av. Alfredo Benavides 5002, Lima 15039, Peru',
      openingHours: 'Todos los días de 12:00 a 18:00',
      typeOfFood: 'peruana',
      averageCost: '$$',
      delivery: false,
      image: '../assets/images/maretazo.jpg',
      rating: 'Riquísimo!! Super recomendado!!',
    },
  ]
};
